// Map memory for streamed worlds without a baked lowres pyramid (live bakes,
// `vantage server`): when a rendered tile is about to be evicted, its meshes
// are snapshotted top-down into one shared atlas render-target and replaced by
// a tiny textured heightfield impostor (~16 KB of atlas at 64 px + ~200 B of
// heights). Impostors persist far beyond the streaming ring, so everywhere the
// camera has BEEN stays on the map — zooming out shows the world you explored
// instead of a void — while the client's memory stays bounded: one fixed
// atlas, farthest-first slot reuse.
//
// This is deliberately client-side. The server streams exactly what it does
// today; what to remember, at what resolution, and how much memory to spend is
// the viewer's quality setting.

import * as THREE from 'three';
import { tileKey, type SurfaceMap } from '../core/index.js';
import { isSharedQuadIndex } from './terrain.js';

/** Impostor heightfield resolution per tile edge (cells; +1 sample apron). */
const GRID = 8;
/** Atlas slots per edge — capacity is its square (1024 remembered tiles). */
const SLOTS = 32;
/** Pending captures beyond this are dropped oldest-first (pan storms). */
const MAX_QUEUE = 12;

/** The tile meshes an eviction hands over for snapshotting. The layer renders
 *  them once, then disposes them exactly like TileManager would have. */
export interface CaptureMeshes {
  terrain?: THREE.Mesh;
  terrainLm?: THREE.Mesh;
  water?: THREE.Mesh;
  lightmapTex?: THREE.DataTexture;
}

interface Pending {
  key: string;
  tileX: number;
  tileZ: number;
  meshes: CaptureMeshes;
  surface: SurfaceMap;
  minY: number;
  maxY: number;
}

interface Impostor {
  key: string;
  slot: number;
  mesh: THREE.Mesh;
  /** (GRID+1)² surface heights for the zoomed-out pivot fallback. */
  heights: Int16Array;
  originX: number;
  originZ: number;
  /** Tile centre, for farthest-first slot reuse. */
  cx: number;
  cz: number;
}

/** Dispose a captured tile's GPU resources the way TileManager does: detach
 *  the shared quad index first (dispose() would delete the shared buffer). */
function disposeCapture(meshes: CaptureMeshes): void {
  for (const mesh of [meshes.terrain, meshes.terrainLm, meshes.water]) {
    if (!mesh) continue;
    mesh.removeFromParent();
    if (isSharedQuadIndex(mesh.geometry.index)) mesh.geometry.setIndex(null);
    mesh.geometry.dispose();
  }
  meshes.lightmapTex?.dispose();
}

export class ImpostorLayer {
  private readonly renderer: THREE.WebGLRenderer;
  private readonly scene: THREE.Scene;
  private readonly tileBlocks: number;
  private readonly resolution: number;
  private readonly rt: THREE.WebGLRenderTarget;
  private readonly material: THREE.ShaderMaterial;
  /** The shared terrain material — captures neutralize its grade/fog/clip
   *  uniforms for one render, and the impostor material re-applies the live
   *  values every frame, so display tuning keeps tracking remembered tiles. */
  private readonly terrain: THREE.ShaderMaterial;
  private readonly captureScene = new THREE.Scene();
  private readonly camera = new THREE.OrthographicCamera();
  private readonly queue: Pending[] = [];
  private readonly byKey = new Map<string, Impostor>();
  private readonly freeSlots: number[] = [];
  private retired = false;

  constructor(renderer: THREE.WebGLRenderer, scene: THREE.Scene, terrainMaterial: THREE.ShaderMaterial, tileBlocks: number, resolution: number) {
    this.renderer = renderer;
    this.scene = scene;
    this.terrain = terrainMaterial;
    this.tileBlocks = tileBlocks;
    this.resolution = resolution;
    for (let i = SLOTS * SLOTS - 1; i >= 0; i--) this.freeSlots.push(i);

    const size = SLOTS * resolution;
    this.rt = new THREE.WebGLRenderTarget(size, size, {
      format: THREE.RGBAFormat,
      // Mipmaps keep far-zoom minification calm; regenerated by three after
      // each capture render. Slots share mip texels at deep levels — invisible
      // at the sub-2-pixel tile sizes where those levels are sampled.
      generateMipmaps: true,
      minFilter: THREE.LinearMipmapLinearFilter,
      magFilter: THREE.LinearFilter,
      depthBuffer: true,
    });
    this.camera.up.set(0, 0, -1); // north up — matches the map's texture V

    const t = terrainMaterial.uniforms;
    this.material = new THREE.ShaderMaterial({
      glslVersion: THREE.GLSL3,
      uniforms: {
        uMap: { value: this.rt.texture },
        uFogColor: t['uFogColor']!,
        uFog: t['uFog']!,
        uFogCenter: t['uFogCenter']!,
        uFogRadial: t['uFogRadial']!,
        uFogDensity: t['uFogDensity']!,
        uExposure: t['uExposure']!,
        uSaturation: t['uSaturation']!,
        uContrast: t['uContrast']!,
        uClipY: t['uClipY']!,
      },
      vertexShader: /* glsl */ `
        uniform vec2 uFogCenter;
        uniform float uFogRadial;
        out vec2 vUv;
        out float vFog;
        out float vWorldY;
        void main() {
          vUv = uv;
          vec4 wp = modelMatrix * vec4(position, 1.0);
          vWorldY = wp.y;
          vec4 mv = viewMatrix * wp;
          vFog = mix(-mv.z, distance(wp.xz, uFogCenter), uFogRadial);
          gl_Position = projectionMatrix * mv;
        }
      `,
      fragmentShader: /* glsl */ `
        precision highp float;
        uniform sampler2D uMap;
        uniform vec3 uFogColor;
        uniform vec2 uFog;
        uniform float uFogDensity;
        uniform float uExposure;
        uniform float uSaturation;
        uniform float uContrast;
        uniform float uClipY;
        in vec2 vUv;
        in float vFog;
        in float vWorldY;
        out vec4 frag;
        vec3 toLinear(vec3 c) {
          return mix(c / 12.92, pow((c + 0.055) / 1.055, vec3(2.4)), step(0.04045, c));
        }
        vec3 toSRGB(vec3 c) {
          c = max(c, vec3(0.0));
          return mix(c * 12.92, 1.055 * pow(c, vec3(1.0 / 2.4)) - 0.055, step(0.0031308, c));
        }
        void main() {
          if (vWorldY > uClipY) discard;
          vec4 t = texture(uMap, vUv);
          if (t.a < 0.5) discard; // void columns captured as transparent
          // Snapshots are captured with a NEUTRAL grade, so the live display
          // settings apply here exactly like they do to hires terrain.
          vec3 c = toLinear(t.rgb) * uExposure;
          float l = dot(c, vec3(0.299, 0.587, 0.114));
          c = mix(vec3(l), c, uSaturation);
          c = max((c - 0.5) * uContrast + 0.5, vec3(0.0));
          float f = smoothstep(uFog.x, uFog.y, vFog) * uFogDensity;
          frag = vec4(toSRGB(mix(c, toLinear(uFogColor), f)), 1.0);
        }
      `,
      alphaToCoverage: true,
      // Skirt quads hang off each tile's rim (see snapshot()); double-sided
      // keeps them visible from every orbit angle without winding gymnastics.
      side: THREE.DoubleSide,
    });
  }

  /** Remembered-tile count (for stats readouts). */
  get count(): number {
    return this.byKey.size;
  }

  /** Snapshot resolution in pixels per tile. */
  get resolutionPx(): number {
    return this.resolution;
  }

  /** How far remembered terrain reaches from (x,z), in blocks — the radius the
   *  viewer's zoom range and fog frontier should keep visible. 0 = nothing
   *  remembered. */
  extentFrom(x: number, z: number): number {
    let extent = 0;
    for (const imp of this.byKey.values()) {
      const d = Math.hypot(imp.cx - x, imp.cz - z);
      if (d > extent) extent = d;
    }
    return extent === 0 ? 0 : extent + this.tileBlocks;
  }

  /** Fixed GPU cost of the atlas (RGBA + mip chain), plus the tiny meshes. */
  get gpuBytes(): number {
    const size = SLOTS * this.resolution;
    return Math.round(size * size * 4 * 1.34) + this.byKey.size * 2048;
  }

  /** Queue an evicted tile's meshes for snapshotting. Takes OWNERSHIP of the
   *  meshes — they are rendered once on a later update() tick, then disposed.
   *  A full queue drops its oldest entry (its meshes are simply disposed). */
  capture(tileX: number, tileZ: number, meshes: CaptureMeshes, surface: SurfaceMap, minY: number, maxY: number): void {
    if (this.retired) {
      disposeCapture(meshes);
      return;
    }
    const key = tileKey(tileX, tileZ);
    // A newer capture of the same tile supersedes a queued one.
    const queued = this.queue.findIndex((p) => p.key === key);
    if (queued >= 0) disposeCapture(this.queue.splice(queued, 1)[0]!.meshes);
    this.queue.push({ key, tileX, tileZ, meshes, surface, minY, maxY });
    if (this.queue.length > MAX_QUEUE) disposeCapture(this.queue.shift()!.meshes);
  }

  /** Forget a tile (it was removed from the manifest). */
  remove(key: string): void {
    const queued = this.queue.findIndex((p) => p.key === key);
    if (queued >= 0) disposeCapture(this.queue.splice(queued, 1)[0]!.meshes);
    const imp = this.byKey.get(key);
    if (imp) this.releaseImpostor(imp);
  }

  /** Drain one pending capture (bounded per frame so a ring of evictions
   *  never stacks its snapshot renders into one frame). Returns whether the
   *  scene changed (the caller redraws + re-runs coverage). */
  update(focusX: number, focusZ: number): boolean {
    const p = this.queue.shift();
    if (!p) return false;
    this.snapshot(p, focusX, focusZ);
    disposeCapture(p.meshes);
    return true;
  }

  /** Hide impostors whose hires tile is resident and fully faded in. */
  applyCoverage(shownHires: ReadonlySet<string>): void {
    for (const imp of this.byKey.values()) imp.mesh.visible = !shownHires.has(imp.key);
  }

  /** Remembered surface height under world (x,z), for the pivot fallback. */
  heightAt(x: number, z: number): number | null {
    const tb = this.tileBlocks;
    const imp = this.byKey.get(tileKey(Math.floor(x / tb), Math.floor(z / tb)));
    if (!imp) return null;
    const step = tb / GRID;
    const i = Math.min(Math.max(Math.round((x - imp.originX) / step), 0), GRID);
    const j = Math.min(Math.max(Math.round((z - imp.originZ) / step), 0), GRID);
    const h = imp.heights[j * (GRID + 1) + i]!;
    return h < 1 ? null : h;
  }

  /** Drop every impostor and stop accepting captures — called when a lowres
   *  pyramid arrives (a finished progressive bake): the baked rings cover the
   *  whole world and supersede anything remembered. */
  retire(): void {
    this.retired = true;
    for (const p of this.queue.splice(0)) disposeCapture(p.meshes);
    for (const imp of [...this.byKey.values()]) this.releaseImpostor(imp);
  }

  dispose(): void {
    this.retire();
    this.rt.dispose();
    this.material.dispose();
  }

  private releaseImpostor(imp: Impostor): void {
    this.scene.remove(imp.mesh);
    imp.mesh.geometry.dispose();
    this.byKey.delete(imp.key);
    this.freeSlots.push(imp.slot);
  }

  /** A free atlas slot, reusing the remembered tile farthest from the focus
   *  when the atlas is full — the same nearest-wins policy streaming uses. */
  private allocSlot(focusX: number, focusZ: number): number {
    const free = this.freeSlots.pop();
    if (free !== undefined) return free;
    let victim: Impostor | null = null;
    let worst = -1;
    for (const imp of this.byKey.values()) {
      const dx = imp.cx - focusX;
      const dz = imp.cz - focusZ;
      const d = dx * dx + dz * dz;
      if (d > worst) {
        worst = d;
        victim = imp;
      }
    }
    this.releaseImpostor(victim!); // capacity ≥ 1, so a victim always exists
    return this.freeSlots.pop()!;
  }

  /** Render the tile's meshes top-down into its atlas slot and swap in the
   *  heightfield impostor. */
  private snapshot(p: Pending, focusX: number, focusZ: number): void {
    const meshes = [p.meshes.terrain, p.meshes.terrainLm, p.meshes.water].filter(Boolean) as THREE.Mesh[];
    if (meshes.length === 0) return;
    const tb = this.tileBlocks;
    const originX = p.tileX * tb;
    const originZ = p.tileZ * tb;

    // Heightfield samples first — an all-void tile bails before it costs an
    // atlas slot or a render.
    const n = GRID + 1;
    const heights = new Int16Array(n * n);
    const surf = p.surface;
    const sample = (i: number, j: number): number => {
      const cx = Math.min(Math.max(Math.round((i * tb) / GRID + originX - surf.originX), 0), surf.width - 1);
      const cz = Math.min(Math.max(Math.round((j * tb) / GRID + originZ - surf.originZ), 0), surf.depth - 1);
      return surf.height[cz * surf.width + cx]!;
    };
    for (let j = 0; j < n; j++) for (let i = 0; i < n; i++) heights[j * n + i] = sample(i, j);
    const idx: number[] = [];
    for (let j = 0; j < GRID; j++) {
      for (let i = 0; i < GRID; i++) {
        const a = j * n + i;
        const b = a + 1;
        const c = a + n;
        const d = c + 1;
        if (heights[a]! < 1 || heights[b]! < 1 || heights[c]! < 1 || heights[d]! < 1) continue;
        idx.push(a, c, d, a, d, b);
      }
    }
    if (idx.length === 0) return; // an all-void tile remembers nothing

    // Recaptures free their old slot first so the alloc below reuses it
    // instead of evicting an innocent neighbour from a full atlas.
    const existing = this.byKey.get(p.key);
    if (existing) this.releaseImpostor(existing);
    const slot = this.allocSlot(focusX, focusZ);
    const res = this.resolution;
    const sx = (slot % SLOTS) * res;
    const sy = Math.floor(slot / SLOTS) * res;

    // Neutralize the world-state uniforms for one clean textured capture; the
    // impostor shader re-applies the live grade/fog per frame. These uniform
    // OBJECTS are shared by the water/lightmap materials, so one save/restore
    // covers every mesh being rendered.
    const u = this.terrain.uniforms;
    const saved = new Map<string, unknown>();
    const neutral: [string, unknown][] = [
      ['uFogDensity', 0],
      ['uBiomeMix', 0],
      ['uHi', -1],
      ['uClipY', 1e9],
      ['uExposure', 1],
      ['uSaturation', 1],
      ['uContrast', 1],
    ];
    for (const [k, v] of neutral) {
      if (!u[k]) continue;
      saved.set(k, u[k]!.value);
      u[k]!.value = v;
    }

    for (const mesh of meshes) this.captureScene.add(mesh);
    // Camera at (0, top, 0) looking straight down with north (-Z) up. In that
    // camera space, x stays world X and "up" is -worldZ — so the frustum is
    // [originX, originX+tb] × [-(originZ+tb), -originZ].
    const cam = this.camera;
    cam.left = originX;
    cam.right = originX + tb;
    cam.top = -originZ;
    cam.bottom = -(originZ + tb);
    cam.near = 1;
    cam.far = p.maxY - p.minY + 32;
    cam.position.set(0, p.maxY + 16, 0);
    cam.lookAt(0, 0, 0);
    cam.updateProjectionMatrix();
    // Ortho frusta here span the whole tile; skip per-mesh culling checks.
    for (const mesh of meshes) mesh.frustumCulled = false;

    const renderer = this.renderer;
    const prevTarget = renderer.getRenderTarget();
    const prevAutoClear = renderer.autoClear;
    const prevColor = renderer.getClearColor(new THREE.Color());
    const prevAlpha = renderer.getClearAlpha();
    this.rt.viewport.set(sx, sy, res, res);
    this.rt.scissor.set(sx, sy, res, res);
    this.rt.scissorTest = true;
    renderer.setRenderTarget(this.rt);
    renderer.setClearColor(0x000000, 0);
    renderer.autoClear = false;
    renderer.clear(true, true);
    renderer.render(this.captureScene, cam);
    renderer.setRenderTarget(prevTarget);
    renderer.setClearColor(prevColor, prevAlpha);
    renderer.autoClear = prevAutoClear;

    for (const [k, v] of saved) u[k]!.value = v;
    this.terrain.uniformsNeedUpdate = true;

    // The heightfield stand-in: the samples above, dipped below the true
    // surface (deeper on slopes) so returning hires terrain wins the depth
    // test cleanly while it fades in.
    const pos: number[] = [];
    const uv: number[] = [];
    // Map the tile onto its slot inset by half a texel per edge — sampling at
    // the exact slot boundary would bilinearly bleed the neighbouring slot
    // (transparent = white seams between remembered tiles).
    const atlasPx = SLOTS * res;
    const u0 = (sx + 0.5) / atlasPx;
    const v0 = (sy + 0.5) / atlasPx;
    const span = (res - 1) / atlasPx;
    let minH = Infinity;
    let maxH = -Infinity;
    for (let j = 0; j < n; j++) {
      for (let i = 0; i < n; i++) {
        const s = j * n + i;
        const h = heights[s]!;
        let slope = 0;
        if (i > 0) slope = Math.max(slope, Math.abs(h - heights[s - 1]!));
        if (i < GRID) slope = Math.max(slope, Math.abs(h - heights[s + 1]!));
        if (j > 0) slope = Math.max(slope, Math.abs(h - heights[s - n]!));
        if (j < GRID) slope = Math.max(slope, Math.abs(h - heights[s + n]!));
        const y = h < 1 ? 0 : h + 1 - 4 - Math.min(slope, 12);
        pos.push(originX + (i * tb) / GRID, y, originZ + (j * tb) / GRID);
        if (h >= 1) {
          if (y < minH) minH = y;
          if (y > maxH) maxH = y;
        }
        // The capture put -Z at the top of the slot; texture v runs bottom-up,
        // so v tracks z directly from the slot's far edge.
        uv.push(u0 + (i / GRID) * span, v0 + (1 - j / GRID) * span);
      }
    }
    if (!Number.isFinite(minH)) {
      this.freeSlots.push(slot); // populated columns but no drawable cell
      return;
    }

    // Rim skirts: neighbouring tiles sample their own surface maps (no shared
    // apron) and dip by their own local slopes, so adjacent impostors meet
    // with hairline height mismatches. Extruding each rim edge downward turns
    // those cracks into slivers of stretched terrain instead of sky.
    const SKIRT = 24;
    const addSkirt = (a: number, b: number) => {
      if (heights[a]! < 1 || heights[b]! < 1) return;
      const base = pos.length / 3;
      for (const s of [a, b]) {
        pos.push(pos[s * 3]!, pos[s * 3 + 1]! - SKIRT, pos[s * 3 + 2]!);
        uv.push(uv[s * 2]!, uv[s * 2 + 1]!);
      }
      idx.push(a, b, base + 1, a, base + 1, base);
    };
    for (let k = 0; k < GRID; k++) {
      addSkirt(k, k + 1); // north rim (j = 0)
      addSkirt(GRID * n + k, GRID * n + k + 1); // south rim
      addSkirt(k * n, (k + 1) * n); // west rim
      addSkirt(k * n + GRID, (k + 1) * n + GRID); // east rim
    }

    const geom = new THREE.BufferGeometry();
    geom.setAttribute('position', new THREE.BufferAttribute(new Float32Array(pos), 3));
    geom.setAttribute('uv', new THREE.BufferAttribute(new Float32Array(uv), 2));
    geom.setIndex(idx);
    const box = new THREE.Box3(new THREE.Vector3(originX, minH - SKIRT, originZ), new THREE.Vector3(originX + tb, maxH, originZ + tb));
    geom.boundingBox = box;
    const sphere = new THREE.Sphere();
    box.getBoundingSphere(sphere);
    geom.boundingSphere = sphere;

    const mesh = new THREE.Mesh(geom, this.material);
    mesh.renderOrder = -1; // under hires like the lowres rings (less overdraw)
    this.scene.add(mesh);
    this.byKey.set(p.key, {
      key: p.key,
      slot,
      mesh,
      heights,
      originX,
      originZ,
      cx: originX + tb / 2,
      cz: originZ + tb / 2,
    });
  }
}
